### ISSUE TITLE
full_requests.py のコメントについて

### ISSUE THREAD

**Issue by NyaShinn1204** [waimaru0713/vote-tracker#2]
書くのを忘れてたので、こちらに書いておきます。

### 定義について
- get_gsessionid_urlがgsessionidというデータ取得に使うurl
- payload_dataが実際に投票結果を取得する際に使うペイロード

### class CustomThreadについて
キャンセル可能なスレッドの定義にしているのは理由があります。
何とも素晴らしいことに、投票データを取得するには、
1. 一度リクエストを送る
2. もう一度リクエストを送る
3. 1で送ったリクエストをキャンセルする。
4. 2で送ったリクエストにデータが返ってくる。
のように素晴らしいことになっています。多分ですが多数決.comのデータ取り扱いをしているFirebaseの仕様っぽいのでこれをどうにかするのはほぼ無理です...
なので、クッソ無理やりにやっています。

コメントと補足説明、別の投票結果にも扱えるようにしたバージョンは以下のzipファイル内に入れておきました。
[comment_full_request.zip](https://github.com/user-attachments/files/17492765/comment_full_request.zip)

**Comment by waimaru0713** [comment]
ありがとうございます。
